### ISSUE TITLE
Question: Can this library return the delta between two graphs?

### ISSUE THREAD

**Issue by wouterbeek** [rubensworks/rdf-isomorphic.js#31]
In some use cases it is useful to print the actual difference between two graphs that are not considered isomorphic (especially when the difference is small).  Is it possible to use the current library for that, or would this require a feature request?

**Comment by rubensworks** [comment]
Calculating deltas is not something that is possible at the moment.
But elements in this library (related to finding bijections between graphs) can definitely be reused in calculating deltas.
I suspect that development effort for enabling this may be quite significant though, but I agree that it would be a very valuable thing to have (either in this library or another that builds upon this).

**Comment by wouterbeek** [comment]
@rubensworks Thanks for the answer!  I'm opening a feature request for this: #32
